version: '3.4'
services:
    
      web:
        container_name: web
        image: 531544/docker:build100
        ports:
         - "3000:3000"
        working_dir: /opt/wildfly
        volumes:
         - /var/log/prod:opt/wildfly/standalone/logs
        environment:
         MYSTACK: qa
        deploy:
          replicas: 2
         healthcheck:
          test:
          - CMD
          - curl localhost:3000
          interval: 20s
          timeout: 10s
          start_period: 60s
       
